language: python

python:
  - "2.7"
  - "2.6"

before_install:
  - export DJANGO_SETTINGS_MODULE=pelican_admin.settings
  - export PYTHONPATH=$HOME/builds/fjcaetano/pelican_admin
  - export PIP_USE_MIRRORS=true

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - "pip install -r requirements.txt"
  - "pip install ."

# command to run tests, e.g. python setup.py test
script:
  - puthon manage.py syncdb --noinput

# database configuration
services: mysql

before_script:
  - mysql -e 'create database pelican_admin_test;'